### ISSUE TITLE
Ubuntu ModuleNotFoundError 

### ISSUE THREAD

**Issue by tbird635** [TKCERT/pfFocus#11]
Installed on Ubuntu , 
I'm getting  a ModuleNotFoundError : No Module named 'pf_focus'  when trying to run pf-format.

I'm sure this is  a noob mistake, but I can't figure it out.

**Comment by mback2k** [comment]
How did you install it? Please see the updated [README.md](https://github.com/TKCERT/pfFocus/blob/master/README.md).

**Comment by tbird635** [comment]
I gave up on the Ubuntu install, being this was  over a month ago. 
I had followed the readme.md that was present on Aug 3rd when I attempted it. 

It worked fine using the docker instructions, so I used that instead. .
